# Generated by Django 4.0.2 on 2022-02-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='myapp.catagory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='myapp.restaurant')),
            ],
        ),
    ]
